name: Auto Deploy to EasyPanel

on:
  push:
    branches:
      - main # Solo deploya cuando hagas push a main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger EasyPanel Deploy
        run: |
          curl -X POST ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIPsHHe7cnmPb/POyO6zH5fP/rSny73W97xkSSVJ1qzru root@622eeeff40f6